### ISSUE TITLE
Comply with Cube 2 license.

### ISSUE THREAD

**Issue by Cynosphere** [HarpNetStudios/cardboard#8]
> If you insist on making a standalone game based on Cube 2, do realize that only the sourcecode is yours to use freely (if you abide by the ZLIB license, see below), while the media is not. You can't simply redistribute the entire package with your modified files, as the majority of game media is not yours to use freely (it is made by many authors with a variety of licences and copyright restrictions). Unless you have explicit permission from the authors, or the readme says explicitly "may be used for any purpose" or similar language, it will be illegal to include in your standalone game based on the engine (you may not assume that just because a file has no explicit license, that it is free of copyright). Therefore, if you wish to produce a standalone game, be prepared to make many of the maps, models, textures, sounds etc from scratch yourself.

**Comment by YellowberryHN** [comment]
Thank you for creating an issue about this. We have already addressed this for the most part, and all of the remaining content that we do not have the license to use will be replaced in the very near future.
